# Generated by Django 3.2.9 on 2022-02-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile NUmber')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('website', models.CharField(max_length=40, verbose_name='YOur Website')),
                ('degree', models.CharField(max_length=40, verbose_name='Degree')),
                ('profile', models.CharField(max_length=40, verbose_name='YOur Profile Name')),
                ('shortdesc', models.TextField(max_length=200, verbose_name='Description')),
                ('desc', models.TextField(max_length=600, verbose_name='About You')),
                ('pimg', models.ImageField(upload_to='about', verbose_name='Your PRofile picture')),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50, verbose_name='Dregree')),
                ('year', models.CharField(max_length=20, verbose_name='Duration Of degree')),
                ('university', models.CharField(max_length=75, verbose_name='University Name')),
                ('desc', models.TextField(max_length=100, verbose_name='Education Description')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50, verbose_name='Job Role')),
                ('year', models.CharField(max_length=20, verbose_name='TOtal Experienc')),
                ('company_name', models.CharField(max_length=75, verbose_name='Company Name')),
                ('desc', models.TextField(max_length=200, verbose_name='Expreenience Description')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Portfolio Title')),
                ('desc', models.TextField(max_length=500, verbose_name='Portfolio Description')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=20, verbose_name='Add YOur skill')),
                ('rate', models.IntegerField(verbose_name='Rate YOurself in %')),
                ('desc', models.TextField(max_length=200, verbose_name='Skill Description')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
